//Address Actions
exports.CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT'
exports.REQUEST_ADDRESS = 'REQUEST_ADDRESS'
exports.RECEIVE_ADDRESS = 'RECEIVE_ADDRESS'
exports.ROW_PRESS = 'ROW_PRESS'

//Route Actions
exports.RESET_STATE = 'RESET_STATE'
exports.ROUTE_POP = 'ROUTE_POP'

//DB Acctions
exports.REQUEST_DB_DATA = 'REQUEST_DB_DATA'
exports.RECEIVE_DB_DATA = 'RECEIVE_DB_DATA'
exports.REQUEST_DB_INSERT = 'REQUEST_DB_INSERT'
exports.REQUEST_DB_DELETE = 'REQUEST_DB_DELETE'
exports.DB_UPDATED = 'DB_UPDATED'
