//Address Actions
exports.CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT'
exports.REQUEST_ADDRESS = 'REQUEST_ADDRESS'
exports.RECEIVE_ADDRESS = 'RECEIVE_ADDRESS'
exports.RECEIVE_EMPTY = 'RECEIVE_EMPTY'
exports.ROW_PRESS = 'ROW_PRESS'

//Route Actions
exports.RESET_STATE = 'RESET_STATE'
exports.ROUTE_POP = 'ROUTE_POP'

//DB Acctions
exports.REQUEST_DB_DATA = 'REQUEST_DB_DATA'
exports.RECEIVE_DB_DATA = 'RECEIVE_DB_DATA'
exports.DB_FAV_ADDED = 'DB_FAV_ADDED'
exports.DB_UNFAV = 'DB_UNFAV'
exports.DB_FAV_REMOVED = 'DB_FAV_REMOVED'
exports.DB_UPDATED = 'DB_UPDATED'

//Download Actions
exports.REQUEST_DOWNLOAD_LIST = 'REQUEST_DOWNLOAD_LIST'
exports.RECEIVE_DOWNLOAD_LIST = 'RECEIVE_DOWNLOAD_LIST'
exports.REQUEST_DOWNLOAD_ITEM = 'REQUEST_DOWNLOAD_ITEM'
exports.RECEIVE_DOWNLOAD_ITEM = 'RECEIVE_DOWNLOAD_ITEM'
exports.UPDATE_DOWNLOAD_ITEM = 'UPDATE_DOWNLOAD_ITEM'
exports.DELETE_DOWNLOAD_ITEM = 'DELETE_DOWNLOAD_ITEM'

exports.ACK_NOTIFICATION = 'ACK_NOTIFICATION'
